.\" Version: 0.3
.\"
.TH ha-sap-convergent  8 "04 Jul 2024" "" "SAPCMControlZone"
.\"
.SH NAME
.\"
ha-sap-convergent - supportconfig plugin for sap-convergent-resource-agents
.PP
.\"
.SH DESCRIPTION
.\"
ha-sap-convergent is a supportconfig plugin for sap-convergent-resource-agents.
It collects information on the Convergent Mediation ControlZone services and the
related Linux HA cluster configuration and logs.
.PP
.\"
.SH RETURN CODES
.\"
\fB0\fR Successful program execution.
.br
\fB>0\fR Usage, syntax or execution errors.
.PP
.\"
.SH FILES
.\"
.TP
/usr/lib/supportconfig/plugins/ha-sap-convergent
the plugin
.\"
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.br
Please report feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
.\"
\fBocf_suse_SAPCMControlZone\fP(7) , \fBsupportconfig\fP(8) , \fBcrm_report\fP(8)
.PP
.\"
.SH AUTHORS
.\"
A.Briel
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2024 SUSE LLC
.br
SAPCMControlZone comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
