.\" Version: 0.0.1
.\"
.TH ocf_suse_SAPCMControlZone 7 "02 Oct 2023" "" "OCF resource agents"
.\"
.SH NAME
SAPCMControlZone \- Manages takeover for SAP HANA Convergent Mediation Control Zone
.PP
.\"
.SH SYNOPSIS
\fBSAPCMControlZone\fP [start | stop | status | monitor | meta\-data | validate\-all | methods | usage ]
.PP
.\"
.SH DESCRIPTION
\fBSAPCMControlZone\fP manages the SAP HANA Convergent Mediation Control Zone.
.PP
....
.\"
.SH EXAMPLES
.\"
.SH FILES
.\"
.SH REQUIREMENTS 
.\"
.SH BUGS
As we currently do not have any code the resource agent is currenty 100% bug-free. We will work on that ;-)
.\"
.SH SEE ALSO
.br

.\"
.SH AUTHORS
.br 
L. Pinne 
.\"
.SH COPYRIGHT
.br
(c) 2023 SUSE LLC
.br
The resource agent SAPHana comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
